### ISSUE TITLE
use of const in strict mode

### ISSUE THREAD

**Issue by asedsami** [hemanth/node-nightly#29]
aseds@asedsami ~/c/l/qa> sudo node-nightly
[sudo] password for aseds: 

/usr/lib/node_modules/node-nightly/cli.js:3
const spawn = require('cross-spawn').spawn;
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:929:3

**Comment by hemanth** [comment]
Please make sure you are on node version `>=4`

**Comment by asedsami** [comment]
```terminal
node -v
```
returns
```terminal
v6.6.0
```

**Comment by hemanth** [comment]
It works fine for me.
