### ISSUE TITLE
404 on initial launch

### ISSUE THREAD

**Issue by krokofant** [hemanth/node-nightly#37]
```
Downloading the nightly version, hang on...
{ HTTPError
    at EventEmitter.ee.on.res (/usr/local/lib/node_modules/node-nightly/node_modules/got/index.js:182:24)
    at emitOne (events.js:96:13)
    at EventEmitter.emit (events.js:189:7)
    at Immediate.setImmediate (/usr/local/lib/node_modules/node-nightly/node_modules/got/index.js:61:8)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
  message: 'Response code 404 (Not Found)',
  host: 'nodejs.org',
  hostname: 'nodejs.org',
  method: 'GET',
  path: '/download/nightly/undefined/node-undefined-darwin-x64.tar.gz',
  statusCode: 404,
  statusMessage: 'Not Found',
  bufferedData: <Buffer > }
```

But after trying out:
```node-nightly --upgrade```

It works!

I thought it was notable that the error specifies `undefined` in the path.

**Comment by hemanth** [comment]
I wonder if this is a side effect of the previous PR.

**Comment by hemanth** [comment]
Did you check this? @icambron

**Comment by icambron** [comment]
Hmm, I thought I had, but apparently not?

**Comment by hemanth** [comment]
It got fixed now, not to worry! 

@krokofant fixed it in the reference PR.
