### ISSUE TITLE
self signed certificate in certificate chain

### ISSUE THREAD

**Issue by chucklu** [hemanth/node-nightly#49]
> node-nightly --inspect --debug-brk build/build.js

Downloading the nightly version, hang on...
FetchError: request to https://nodejs.org/download/nightly/index.json failed, reason: self signed certificate in certificate chain
    at ClientRequest.<anonymous> (C:\Users\clu\AppData\Roaming\npm\node_modules\node-nightly\node_modules\node-fetch\index.js:133:11)
    at ClientRequest.emit (events.js:310:20)
    at TLSSocket.socketErrorListener (_http_client.js:426:9)
    at TLSSocket.emit (events.js:310:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  type: 'system',
  errno: 'SELF_SIGNED_CERT_IN_CHAIN',
  code: 'SELF_SIGNED_CERT_IN_CHAIN'
}

**Comment by chucklu** [comment]
Is it possible to bypass this error?

**Comment by chucklu** [comment]
Try the network at home, got another error 
Downloading the nightly version, hang on...
FetchError: request to https://nodejs.org/download/nightly/index.json failed, reason: Client network socket disconnected before secure TLS connection was established
    at ClientRequest.<anonymous> (C:\Users\clu\AppData\Roaming\npm\node_modules\node-nightly\node_modules\node-fetch\index.js:133:11)
    at ClientRequest.emit (events.js:310:20)
    at TLSSocket.socketErrorListener (_http_client.js:426:9)
    at TLSSocket.emit (events.js:310:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  type: 'system',
  errno: 'ECONNRESET',
  code: 'ECONNRESET'
}

**Comment by chucklu** [comment]
Client network socket disconnected before secure TLS connection was established caused by proxy, I did not have proxy at home.
Turn off the npm proxy, then I got the same error  self signed certificate in certificate chain

**Comment by chucklu** [comment]
Tried to `npm set strict-ssl false`, still have the same problem

**Comment by chucklu** [comment]
The `self signed certificate in certificate chain` problem was caused by [Forcepoint](https://www.forcepoint.com/) used in company, just disable it can bypass this problem.
