### ISSUE TITLE
Error: EPERM: operation not permitted, rename node-nightly required

### ISSUE THREAD

**Issue by chucklu** [hemanth/node-nightly#50]
> node-nightly --inspect --debug-brk build/build.js

Downloading the nightly version, hang on...
Error: EPERM: operation not permitted, rename 'C:\Users\clu\AppData\Roaming\npm\node_modules\node-nightly/node-v15.0.0-nightly20200518ef1eb8d439-win-x64' -> 'C:\Users\clu\AppData\Roaming\npm\node_modules\node-nightly/node-nightly'
    at renameSync (fs.js:661:3)
    at C:\Users\clu\AppData\Roaming\npm\node_modules\node-nightly\index.js:45:9 {
  errno: -4048,
  syscall: 'rename',
  code: 'EPERM',
  path: 'C:\\Users\\clu\\AppData\\Roaming\\npm\\node_modules\\node-nightly/node-v15.0.0-nightly20200518ef1eb8d439-win-x64',
  dest: 'C:\\Users\\clu\\AppData\\Roaming\\npm\\node_modules\\node-nightly/node-nightly'
}

**Comment by chucklu** [comment]
rename the folder then got 
 New nightly available. To upgrade: `node-nightly --upgrade`

**Comment by chucklu** [comment]
node-nightly -v
 New nightly available. To upgrade: `node-nightly --upgrade`
v15.0.0-nightly20200518ef1eb8d439

**Comment by chucklu** [comment]
It's weird, after upgrade still same version

PS D:\Edenred\UK\UK60\Connect_Incentive_Frontend> node-nightly --upgrade
Checking for update...
Deleting old version
Deleted!
Installing newer version..
node-nightly is available on your CLI!
PS D:\Edenred\UK\UK60\Connect_Incentive_Frontend> node-nightly -v
v15.0.0-nightly20200518ef1eb8d439
